### ISSUE TITLE
Remove unused images and favicons

### ISSUE THREAD

**Issue by ajayns** [wdlsvnit/wdlsvnit.github.io#12]
The assets folder seems to currently bloated with favicons and so on of the GDG logo. 
Should this be cleared? @sumedh123 @kvnamipara

**Comment by ajayns** [comment]
Okay rather replace them with the new Web Dev Labs logo maybe?

**Comment by lunaticmonk** [comment]
Please do it.

**Comment by ajayns** [comment]
@sumedh123 Should I remove or replace them? And are we going on with the Web Dev Labs logo itself? There are no plans of renaming it to Dev Labs yet?

**Comment by lunaticmonk** [comment]
you can go ahead for the current logo. we are discussing to make a new domain for mobile development under webdevlabs rather than renaming it.

**Comment by ajayns** [comment]
@sumedh123 Alright then
