### ISSUE TITLE
WebDeb Labs Logo on navbar

### ISSUE THREAD

**Issue by ajayns** [wdlsvnit/wdlsvnit.github.io#17]
On the top navbar the brand image we use is the WDL logo with the text beneath it. This isn't really visible: 
![image](https://user-images.githubusercontent.com/20743219/38159912-d9162600-34d0-11e8-9b43-7305787fa7b5.png)

I'd suggest we use just the text for the top navbar as we already have a logo over our hero image. 
@sumedh123 Opinions?

**Comment by lunaticmonk** [comment]
@ajayns Okay sure. Please make a pr if you çan.
