### ISSUE TITLE
WebDev Labs logo overlayed on hero image not perfectly aligned

### ISSUE THREAD

**Issue by ajayns** [wdlsvnit/wdlsvnit.github.io#6]
![image](https://user-images.githubusercontent.com/20743219/37271815-7b7441ba-25fa-11e8-8ead-3c58b199e055.png)

As you can see from the screenshot, the logo is slightly towards the left.

**Comment by lunaticmonk** [comment]
@ajayns 
<img width="1440" alt="screen shot 2018-03-12 at 3 08 57 pm" src="https://user-images.githubusercontent.com/17925669/37276312-5d164a94-2607-11e8-92ab-19b54a85c4cc.png">
<img width="1440" alt="screen shot 2018-03-12 at 3 09 07 pm" src="https://user-images.githubusercontent.com/17925669/37276315-5ee03808-2607-11e8-8af9-d203aa3666a9.png">

**Comment by lunaticmonk** [comment]
Seems logo has also to be shifted to right by 10 pixels.

**Comment by ajayns** [comment]
This is solved by #7. Closing issue.
